In [1]:
import pandas as pd
path=r"C:\Hope AI\course\NLP\New folder\tam.txt"
data=pd.read_csv(path,sep='\t',header=None)
data.head()

,0,1,2
0,I slept.,நான் தூங்கினேன்.,CC-BY 2.0 (France) Attribution: tatoeba.org #3...
1,Calm down.,அமைதியாக இருங்கள்,CC-BY 2.0 (France) Attribution: tatoeba.org #4...
2,I'll walk.,நான் நடப்பேன்.,CC-BY 2.0 (France) Attribution: tatoeba.org #2...
3,Who is he?,அவன் யார்?,CC-BY 2.0 (France) Attribution: tatoeba.org #3...
4,Who knows?,யாருக்குத் தெரியும்?,CC-BY 2.0 (France) Attribution: tatoeba.org #2...


In [2]:
data[0]

0                                               I slept.
1                                             Calm down.
2                                             I'll walk.
3                                             Who is he?
4                                             Who knows?
                             ...                        
196    Tom says he doesn't think he can do that by hi...
197    People who live in glass houses shouldn't thro...
198    It's been a long time since I've heard anyone ...
199    If you want your workers to be happy, you need...
200    It's my fault that the cake was burned. I was ...
Name: 0, Length: 201, dtype: object

In [3]:
eng_txt=data[0]
tam_txt=data[1]

In [4]:
eng_txt

0                                               I slept.
1                                             Calm down.
2                                             I'll walk.
3                                             Who is he?
4                                             Who knows?
                             ...                        
196    Tom says he doesn't think he can do that by hi...
197    People who live in glass houses shouldn't thro...
198    It's been a long time since I've heard anyone ...
199    If you want your workers to be happy, you need...
200    It's my fault that the cake was burned. I was ...
Name: 0, Length: 201, dtype: object

In [5]:
tam_txt

0                                       நான் தூங்கினேன்.
1                                      அமைதியாக இருங்கள்
2                                         நான் நடப்பேன்.
3                                             அவன் யார்?
4                                   யாருக்குத் தெரியும்?
                             ...                        
196    என் ஒருவனால் மட்டுமே அதை செய்ய முடியாது என்று ...
197      கண்ணாடி வீட்டில் வசிப்பவகள் கல்லை எறியக் கூடாது
198    ஒருவர் அந்த வார்த்தையைப் பயன் படுத்துவதைக் கேட...
199    உங்களுடைய வேலையாட்கள் மகிழ்ச்சியாக இருக்க வேண்...
200    என்னுடையத் தவறினால் கேக்கானதுக் கருகிப் போனது....
Name: 1, Length: 201, dtype: object

In [6]:
def tokenize(sentences):
    tokens=[s.split() for s in sentences]
    statements=[]
    for i in tokens:
        statements.append(i)
    return statements

In [7]:
eng_statement=tokenize(eng_txt)
tam_statement=tokenize(tam_txt)

In [8]:
eng_statement

[['I', 'slept.'],
 ['Calm', 'down.'],
 ["I'll", 'walk.'],
 ['Who', 'is', 'he?'],
 ['Who', 'knows?'],
 ['She', 'smiled.'],
 ['Talk', 'to', 'me!'],
 ['Who', 'is', 'she?'],
 ['Go', 'to', 'sleep.'],
 ['It', 'may', 'rain.'],
 ['She', 'bit', 'him.'],
 ['She', 'hit', 'him.'],
 ['She', 'is', 'kind.'],
 ['She', 'is', 'eight.'],
 ['Where', 'are', 'we?'],
 ['Keep', 'in', 'touch!'],
 ['See', 'you', 'again.'],
 ['Give', 'it', 'to', 'her.'],
 ['I', 'ate', 'too', 'much.'],
 ["I'll", 'see', 'to', 'it.'],
 ["It's", 'up', 'to', 'you.'],
 ['Leave', 'it', 'to', 'me.'],
 ['Listen', 'to', 'this!'],
 ["That's", 'the', 'way.'],
 ['Come', 'and', 'see', 'me.'],
 ["Don't", 'lie', 'to', 'me.'],
 ['He', 'began', 'to', 'run.'],
 ['He', 'just', 'arrived.'],
 ['He', 'likes', 'to', 'run.'],
 ['How', 'is', 'your', 'dad?'],
 ['I', 'want', 'to', 'sleep.'],
 ["I'm", 'able', 'to', 'run.'],
 ['Raise', 'your', 'hand.'],
 ['What', 'did', 'he', 'say?'],
 ['When', 'can', 'we', 'eat?'],
 ['Come', 'and', 'help', 'us.'],
 ['He', '

In [9]:
from gensim.models import Word2Vec
eng_w2v=Word2Vec(eng_statement,min_count=3)
tam_w2v=Word2Vec(tam_statement,min_count=3)

In [10]:
eng_w2v.wv.vectors

array([[-6.4677536e-04,  3.7476953e-04,  5.2000657e-03, ...,
        -7.0953197e-03,  8.5662975e-04,  6.2798699e-03],
       [-8.6760465e-03,  3.7229049e-03,  5.2374247e-03, ...,
        -2.4329184e-03, -9.5801912e-03,  4.4188472e-03],
       [-1.0230980e-05,  3.1753946e-03, -6.7515578e-03, ...,
         4.6225646e-04,  8.1244465e-03, -7.1127317e-03],
       ...,
       [ 4.2106914e-03,  2.4218776e-03, -4.1488564e-04, ...,
        -4.7752820e-03,  6.1153132e-03, -7.1437052e-03],
       [-7.4103619e-03,  6.6182576e-03, -3.3724105e-03, ...,
        -8.7507246e-03,  6.5029035e-03, -6.2194122e-03],
       [-6.2618987e-04,  1.4303069e-03, -1.1781513e-03, ...,
        -3.1996763e-03, -4.6719545e-03, -4.3688007e-03]],
      shape=(74, 100), dtype=float32)

In [11]:
eng_w2v.wv.index_to_key

['to',
 'of',
 'I',
 'He',
 'the',
 'She',
 'is',
 'a',
 'and',
 'Tom',
 'you',
 "I'm",
 'him.',
 'in',
 'he',
 'your',
 'me.',
 'it',
 'has',
 'that',
 'want',
 'out',
 'my',
 'know',
 'have',
 'When',
 'you.',
 "It's",
 'got',
 'The',
 'afraid',
 'with',
 'come.',
 'Do',
 'see',
 'been',
 'was',
 'not',
 'on',
 'do',
 'be',
 'We',
 'money.',
 'him',
 'up.',
 'go',
 'Come',
 'her.',
 'Go',
 'when',
 'think',
 'by',
 'after',
 'went',
 'them',
 'lot',
 'us',
 'am',
 'she',
 'ran',
 'me',
 'told',
 'kind',
 'now.',
 'can',
 'did',
 'What',
 'run.',
 'began',
 "Don't",
 'are',
 'sleep.',
 'Who',
 "I'll"]

In [12]:
eng_w2v.wv.most_similar("he")

[('kind', 0.2609277069568634),
 ('it', 0.2512105703353882),
 ('she', 0.20039664208889008),
 ('him', 0.1963692307472229),
 ('us', 0.1823830008506775),
 ('He', 0.17930914461612701),
 ('was', 0.1745443344116211),
 ('know', 0.17202825844287872),
 ('that', 0.1666974425315857),
 ('of', 0.1645875722169876)]

In [13]:
tam_w2v.wv.most_similar("நான்")

[('பயம்', 0.21887502074241638),
 ('எனக்கு', 0.2161451280117035),
 ('செய்து', 0.19522787630558014),
 ('பணம்', 0.15199832618236542),
 ('ஓட', 0.14167778193950653),
 ('எப்படி', 0.10838941484689713),
 ('வெளியே', 0.09960979968309402),
 ('அதை', 0.09643375873565674),
 ('இது', 0.09311801940202713),
 ('நீ', 0.0930355116724968)]

In [14]:
eng_w2v.save("Eng_model_w2v.bin")
tam_w2v.save("Tam_model_w2v.bin")

In [15]:
eng_w2v.vector_size

100

In [16]:
def add_soseos(sentences):
    sos="<SOS>"
    eos="<EOS>"
    statements=[f"{sos} {sequences} {eos}"for sequences in sentences]
    return statements

In [17]:
eng_soseos=add_soseos(eng_txt)
tam_soseos=add_soseos(tam_txt)

In [18]:
eng_soseos

['<SOS> I slept. <EOS>',
 '<SOS> Calm down. <EOS>',
 "<SOS> I'll walk. <EOS>",
 '<SOS> Who is he? <EOS>',
 '<SOS> Who knows? <EOS>',
 '<SOS> She smiled. <EOS>',
 '<SOS> Talk to me! <EOS>',
 '<SOS> Who is she? <EOS>',
 '<SOS> Go to sleep. <EOS>',
 '<SOS> It may rain. <EOS>',
 '<SOS> She bit him. <EOS>',
 '<SOS> She hit him. <EOS>',
 '<SOS> She is kind. <EOS>',
 '<SOS> She is eight. <EOS>',
 '<SOS> Where are we? <EOS>',
 '<SOS> Keep in touch! <EOS>',
 '<SOS> See you again. <EOS>',
 '<SOS> Give it to her. <EOS>',
 '<SOS> I ate too much. <EOS>',
 "<SOS> I'll see to it. <EOS>",
 "<SOS> It's up to you. <EOS>",
 '<SOS> Leave it to me. <EOS>',
 '<SOS> Listen to this! <EOS>',
 "<SOS> That's the way. <EOS>",
 '<SOS> Come and see me. <EOS>',
 "<SOS> Don't lie to me. <EOS>",
 '<SOS> He began to run. <EOS>',
 '<SOS> He just arrived. <EOS>',
 '<SOS> He likes to run. <EOS>',
 '<SOS> How is your dad? <EOS>',
 '<SOS> I want to sleep. <EOS>',
 "<SOS> I'm able to run. <EOS>",
 '<SOS> Raise your hand. <EO

In [19]:
from tensorflow.keras.layers import LSTM,Dense,Embedding,Input
from tensorflow.keras.models import Model
import tensorflow as tf
from tensorflow.keras.models import Sequential
import numpy as np

In [20]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [21]:
def tokenize_padding(soseos_tokens,length,pad):
    tokenizer=Tokenizer(filters="")
    tokenizer.fit_on_texts(soseos_tokens)
    sequences=tokenizer.texts_to_sequences(soseos_tokens)

    maxlen = max(len(seq) for seq in sequences)+2

    padded_sequence=pad_sequences(sequences,maxlen=maxlen,padding=pad)
    return sequences,padded_sequence,tokenizer,maxlen

In [22]:
eng_sequences,paded_eng_sequences,eng_tokenizer,eng_maxlen=tokenize_padding(eng_soseos,15,"post")
tam_sequences,padded_tam_sequences,tam_tokenizer,tam_maxlen=tokenize_padding(tam_soseos,15,"post")

In [23]:
paded_eng_sequences
padded_tam_sequences

array([[  1,   3, 102, ...,   0,   0,   0],
       [  1,  41, 103, ...,   0,   0,   0],
       [  1,   3, 104, ...,   0,   0,   0],
       ...,
       [  1, 544,  20, ...,   0,   0,   0],
       [  1,  92, 548, ...,   0,   0,   0],
       [  1, 555, 556, ...,   2,   0,   0]], shape=(201, 15), dtype=int32)

In [24]:
eng_maxlen

23

In [25]:
tam_maxlen

15

In [26]:
maxlen = max(len(seq) for seq in tam_sequences)
print("Max Length:",maxlen)

Max Length: 13


In [27]:
eng_sequences

[[1, 5, 129, 2],
 [1, 130, 131, 2],
 [1, 56, 79, 2],
 [1, 34, 9, 132, 2],
 [1, 34, 133, 2],
 [1, 8, 80, 2],
 [1, 134, 3, 135, 2],
 [1, 34, 9, 136, 2],
 [1, 20, 3, 57, 2],
 [1, 14, 81, 137, 2],
 [1, 8, 138, 15, 2],
 [1, 8, 139, 15, 2],
 [1, 8, 9, 140, 2],
 [1, 8, 9, 141, 2],
 [1, 58, 43, 142, 2],
 [1, 44, 17, 143, 2],
 [1, 28, 12, 144, 2],
 [1, 145, 14, 3, 45, 2],
 [1, 5, 146, 147, 82, 2],
 [1, 56, 28, 3, 148, 2],
 [1, 24, 83, 3, 29, 2],
 [1, 59, 14, 3, 21, 2],
 [1, 84, 3, 149, 2],
 [1, 85, 7, 150, 2],
 [1, 35, 11, 28, 21, 2],
 [1, 36, 151, 3, 21, 2],
 [1, 6, 60, 3, 61, 2],
 [1, 6, 86, 152, 2],
 [1, 6, 153, 3, 61, 2],
 [1, 62, 9, 22, 154, 2],
 [1, 5, 25, 3, 57, 2],
 [1, 16, 155, 3, 61, 2],
 [1, 156, 22, 157, 2],
 [1, 37, 46, 6, 158, 2],
 [1, 18, 47, 30, 159, 2],
 [1, 35, 11, 87, 88, 2],
 [1, 6, 9, 89, 90, 2],
 [1, 5, 31, 3, 20, 63, 2],
 [1, 5, 32, 26, 82, 2],
 [1, 5, 91, 10, 160, 2],
 [1, 5, 64, 3, 161, 2],
 [1, 85, 92, 162, 2],
 [1, 163, 43, 23, 164, 2],
 [1, 64, 93, 4, 21, 2],
 [1, 16

In [28]:
tam_sequences

[[1, 3, 102, 2],
 [1, 41, 103, 2],
 [1, 3, 104, 2],
 [1, 5, 42, 2],
 [1, 105, 106, 2],
 [1, 4, 107, 2],
 [1, 10, 108, 2],
 [1, 4, 42, 2],
 [1, 18, 109, 2],
 [1, 110, 111, 2],
 [1, 4, 29, 112, 2],
 [1, 4, 29, 113, 2],
 [1, 4, 114, 2],
 [1, 115, 116, 117, 2],
 [1, 118, 43, 119, 2],
 [1, 120, 44, 2],
 [1, 121, 122, 2],
 [1, 30, 123, 2],
 [1, 3, 14, 124, 2],
 [1, 31, 3, 45, 2],
 [1, 46, 125, 19, 2],
 [1, 10, 126, 2],
 [1, 127, 128, 2],
 [1, 20, 129, 130, 2],
 [1, 131, 47, 48, 2],
 [1, 10, 132, 133, 2],
 [1, 5, 32, 49, 2],
 [1, 5, 134, 33, 2],
 [1, 5, 32, 135, 136, 2],
 [1, 137, 138, 34, 139, 2],
 [1, 3, 140, 21, 2],
 [1, 50, 32, 141, 2],
 [1, 142, 143, 2],
 [1, 5, 22, 144, 2],
 [1, 23, 145, 51, 146, 2],
 [1, 52, 53, 54, 147, 2],
 [1, 5, 55, 148, 2],
 [1, 3, 56, 57, 12, 2],
 [1, 13, 149, 150, 2],
 [1, 3, 7, 151, 152, 2],
 [1, 3, 153, 154, 155, 2],
 [1, 156, 58, 157, 2],
 [1, 158, 59, 159, 160, 2],
 [1, 13, 60, 161, 2],
 [1, 24, 162, 163, 164, 165, 2],
 [1, 166, 167, 2],
 [1, 5, 168, 169, 33

In [29]:
padded_tam_sequences

array([[  1,   3, 102, ...,   0,   0,   0],
       [  1,  41, 103, ...,   0,   0,   0],
       [  1,   3, 104, ...,   0,   0,   0],
       ...,
       [  1, 544,  20, ...,   0,   0,   0],
       [  1,  92, 548, ...,   0,   0,   0],
       [  1, 555, 556, ...,   2,   0,   0]], shape=(201, 15), dtype=int32)

In [30]:
padded_tam_sequences[:,0]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1], dtype=int32)

In [31]:
eng_vocab_size=len(eng_tokenizer.word_index)+1
tam_vocab_size=len(tam_tokenizer.word_index)+1
print(eng_vocab_size)
print(tam_vocab_size)

434
565


In [32]:
tam_tokenizer.word_index["<eos>"]

2

In [33]:
decoder_input_seq=np.zeros_like(padded_tam_sequences)
decoder_input_seq[:,1:]=padded_tam_sequences[:,:-1]
decoder_input_seq[:,0]=tam_tokenizer.word_index["<sos>"]

decoder_output_seq=np.eye(tam_vocab_size)[padded_tam_sequences]

In [34]:
decoder_input_seq

array([[  1,   1,   3, ...,   0,   0,   0],
       [  1,   1,  41, ...,   0,   0,   0],
       [  1,   1,   3, ...,   0,   0,   0],
       ...,
       [  1,   1, 544, ...,   0,   0,   0],
       [  1,   1,  92, ...,   2,   0,   0],
       [  1,   1, 555, ...,  97,   2,   0]], shape=(201, 15), dtype=int32)

In [35]:
decoder_output_seq[0]

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], shape=(15, 565))

In [36]:
eng_tokenizer.word_index.items()

dict_items([('<sos>', 1), ('<eos>', 2), ('to', 3), ('of', 4), ('i', 5), ('he', 6), ('the', 7), ('she', 8), ('is', 9), ('a', 10), ('and', 11), ('you', 12), ('tom', 13), ('it', 14), ('him.', 15), ("i'm", 16), ('in', 17), ('when', 18), ('do', 19), ('go', 20), ('me.', 21), ('your', 22), ('my', 23), ("it's", 24), ('want', 25), ('that', 26), ('has', 27), ('see', 28), ('you.', 29), ('we', 30), ('have', 31), ('know', 32), ('out', 33), ('who', 34), ('come', 35), ("don't", 36), ('what', 37), ('come.', 38), ('with', 39), ('afraid', 40), ('be', 41), ('got', 42), ('are', 43), ('keep', 44), ('her.', 45), ('did', 46), ('can', 47), ('up.', 48), ('him', 49), ('money.', 50), ('this', 51), ('on', 52), ('not', 53), ('was', 54), ('been', 55), ("i'll", 56), ('sleep.', 57), ('where', 58), ('leave', 59), ('began', 60), ('run.', 61), ('how', 62), ('now.', 63), ('walk', 64), ('kind', 65), ('told', 66), ('me', 67), ('ran', 68), ('am', 69), ('all', 70), ('us', 71), ('lot', 72), ('them', 73), ('went', 74), ('after

In [37]:
from gensim.models import Word2Vec
eng_model=Word2Vec.load("Eng_model_w2v.bin")
tam_model=Word2Vec.load("Tam_model_w2v.bin")

In [38]:
len(eng_tokenizer.word_index)

433

In [39]:
eng_model.vector_size

100

In [40]:
eng_tokenizer.word_index.items()

dict_items([('<sos>', 1), ('<eos>', 2), ('to', 3), ('of', 4), ('i', 5), ('he', 6), ('the', 7), ('she', 8), ('is', 9), ('a', 10), ('and', 11), ('you', 12), ('tom', 13), ('it', 14), ('him.', 15), ("i'm", 16), ('in', 17), ('when', 18), ('do', 19), ('go', 20), ('me.', 21), ('your', 22), ('my', 23), ("it's", 24), ('want', 25), ('that', 26), ('has', 27), ('see', 28), ('you.', 29), ('we', 30), ('have', 31), ('know', 32), ('out', 33), ('who', 34), ('come', 35), ("don't", 36), ('what', 37), ('come.', 38), ('with', 39), ('afraid', 40), ('be', 41), ('got', 42), ('are', 43), ('keep', 44), ('her.', 45), ('did', 46), ('can', 47), ('up.', 48), ('him', 49), ('money.', 50), ('this', 51), ('on', 52), ('not', 53), ('was', 54), ('been', 55), ("i'll", 56), ('sleep.', 57), ('where', 58), ('leave', 59), ('began', 60), ('run.', 61), ('how', 62), ('now.', 63), ('walk', 64), ('kind', 65), ('told', 66), ('me', 67), ('ran', 68), ('am', 69), ('all', 70), ('us', 71), ('lot', 72), ('them', 73), ('went', 74), ('after

In [41]:
def embedding_matrix(tokenizer,w2v_model):
    vocab_size=len(tokenizer.word_index)+1
    embedding_matrix=np.zeros((vocab_size,w2v_model.vector_size))

    for word,i in tokenizer.word_index.items():
        try:
            vector=w2v_model.wv[word]
            embedding_matrix[i]=vector
        except KeyError:
            pass
    return embedding_matrix

In [42]:
eng_embdd_matrix=embedding_matrix(eng_tokenizer,eng_model)
tam_embdd_matrix=embedding_matrix(tam_tokenizer,tam_model)

In [43]:
print(eng_embdd_matrix.shape)
print(tam_embdd_matrix.shape)

(434, 100)
(565, 100)


In [44]:
def create_seq2seq_model(input_seq_length,output_seq_length,input_vocab_size,output_vocab_size,hidden_units,eng_embedding,tam_embedding):
    encoder_input=Input(shape=(input_seq_length,))
    encoder_embedding=Embedding(input_vocab_size,hidden_units,trainable=False,weights=[eng_embedding])(encoder_input)

    encoder_lstm = LSTM(hidden_units, return_state=True)
    _, encoder_state_h, encoder_state_c = encoder_lstm(encoder_embedding)
    
    
    encoder_states = [encoder_state_h, encoder_state_c]
    
    decoder_inputs=Input(shape=(output_seq_length,))
    decoder_embedding=Embedding(output_vocab_size,hidden_units,weights=[tam_embedding],trainable=False)(decoder_inputs)
    
    decoder_lstm=LSTM(hidden_units,return_sequences=True,return_state=True)
    decoder_outputs,_,_=decoder_lstm(decoder_embedding,initial_state=[encoder_state_h,encoder_state_c])
    decoder_dense=Dense(output_vocab_size,activation='softmax')
    decoder_outputs=decoder_dense(decoder_outputs)

    model=Model([encoder_input,decoder_inputs],decoder_outputs)
    return model

In [45]:
target_sequences=tf.keras.utils.to_categorical(padded_tam_sequences,num_classes=tam_vocab_size)

In [46]:
model=create_seq2seq_model(eng_maxlen,tam_maxlen,eng_vocab_size,tam_vocab_size,100,eng_embdd_matrix,tam_embdd_matrix)

In [47]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [48]:
model.fit([paded_eng_sequences,padded_tam_sequences],decoder_output_seq,batch_size=32,epochs=100,validation_split=0.2)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 4s 206ms/step - accuracy: 0.5004 - loss: 6.3249 - val_accuracy: 0.4748 - val_loss: 6.3077
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6217 - loss: 6.2634 - val_accuracy: 0.4748 - val_loss: 6.2018
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6217 - loss: 5.9389 - val_accuracy: 0.4748 - val_loss: 5.3746
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6217 - loss: 4.2371 - val_accuracy: 0.4748 - val_loss: 3.8873
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6217 - loss: 2.8417 - val_accuracy: 0.4748 - val_loss: 3.3989
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6750 - loss: 2.2649 - val_accuracy: 0.5415 - val_loss: 3.3211
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6883 - loss: 2.0306 - val_accuracy: 0.5415 - val_loss: 3.2181
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6883 - loss: 1.9335 - val_accuracy: 0.5415 - val_loss

In [61]:
in_seq="<sos> i slept <eos>"
in_seq=eng_tokenizer.texts_to_sequences([in_seq])
in_seq=pad_sequences(in_seq,maxlen=eng_maxlen,padding='post')

In [62]:
pred=model.predict([in_seq,np.zeros((1,tam_maxlen))])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step


In [63]:
pred_token=np.argmax(pred,axis=-1)[0]

In [64]:
word={i:w for w,i in tam_tokenizer.word_index.items()}

In [65]:
word

{1: '<sos>',
 2: '<eos>',
 3: 'நான்',
 4: 'அவள்',
 5: 'அவன்',
 6: 'டாம்',
 7: 'ஒரு',
 8: 'என்று',
 9: 'அவனுக்கு',
 10: 'என்னிடம்',
 11: 'நீ',
 12: 'வேண்டும்',
 13: 'எனக்கு',
 14: 'நிறைய',
 15: 'தெரியும்',
 16: 'இது',
 17: 'இந்த',
 18: 'போய்',
 19: 'இருக்கிறது',
 20: 'அந்த',
 21: 'விரும்புகிறேன்',
 22: 'என்ன',
 23: 'எப்பொழுது',
 24: 'நாங்கள்',
 25: 'உன்னிடம்',
 26: 'என்',
 27: 'பயம்',
 28: 'அவர்கள்',
 29: 'அவனைக்',
 30: 'அவளிடம்',
 31: 'அதை',
 32: 'ஓட',
 33: 'வந்தான்',
 34: 'எப்படி',
 35: 'எனக்குத்',
 36: 'பணம்',
 37: 'செல்ல',
 38: 'செய்து',
 39: 'வெளியே',
 40: 'மேரியுடன்',
 41: 'அமைதியாக',
 42: 'யார்?',
 43: 'எங்கே',
 44: 'இரு',
 45: 'பார்க்கிறேன்',
 46: 'உன்',
 47: 'வந்து',
 48: 'பார்',
 49: 'ஆரம்பித்தான்',
 50: 'என்னால்',
 51: 'சாப்பிட',
 52: 'வா',
 53: 'எங்களுக்கு',
 54: 'உதவி',
 55: 'இன்னும்',
 56: 'இப்பொழுது',
 57: 'போக',
 58: 'எங்களுடைய',
 59: 'என்னுடைய',
 60: 'முன்னால்',
 61: 'மூன்று',
 62: 'என்பது',
 63: 'போகத்',
 64: 'நடக்க',
 65: 'ஆடை',
 66: 'இதை',
 67: 'அவனுக்குக்',
 68: 'கொ

In [66]:
decoded=[]
for token in pred_token:
    if token==0:
        continue
    words=word.get(token)
    if words=="<eos>":
        break
    if words is not None:
        decoded.append(words)
    decoded_sentence=''.join(decoded)
    print(decoded_sentence)
        

<sos>
<sos>நான்
<sos>நான்நான்
